### ISSUE TITLE
Panache types seem to be not included in the NPM package

### ISSUE THREAD

**Issue by mindreframer** [oscarpas/panache#14]
**Describe the bug**
It seem that the types are missing in the distribution. See screenshots + file listing. 

```
$ pwd
node_modules/panache-react
$ find dist/
dist/
dist//sheet.d.ts
dist//main.d.ts
dist//provider
dist//provider/provider.d.ts
dist//utils
dist//utils/htmlTags.d.ts
dist//factory.d.ts
dist//panache.cjs.js
dist//provider.d.ts
dist//panache.esm.js
dist//sheet
dist//sheet/sheet.d.ts
dist//factory
dist//factory/factory.d.ts
```

**To Reproduce**
- Install package v 0.2.0
- try using it in Visual Studio Code

**Expected behavior**
Autocompletion should work. 

**Screenshots**

<img width="932" alt="Screenshot 2021-03-31 at 12 17 42" src="https://user-images.githubusercontent.com/1232/113129622-661ed100-921b-11eb-9867-27ff7cc91290.png">
<img width="767" alt="Screenshot 2021-03-31 at 12 18 02" src="https://user-images.githubusercontent.com/1232/113129647-6c14b200-921b-11eb-92f3-8354f56125f6.png">

**Comment by oscarpas** [comment]
Hi @mindreframer – thanks for reporting the issue, you're right that the typings had some issues.

Typings for the component creators (`panache.div` and so on) should be fixed in 0.3.0, would be great if you could upgrade and give it a spin.

There are some other areas that still needs declarations/improvements but this upgrade should cover the must crucial parts.

**Comment by mindreframer** [comment]
Hey @oscarpas, it works with `0.3.0`, thanks!

**Comment by mindreframer** [comment]
I'll close this, I hope other improvements that you mention might be covered by a separate issue, if needed.
