### ISSUE TITLE
It is not clear what version is released / how the build actually worked

### ISSUE THREAD

**Issue by mindreframer** [oscarpas/panache#16]
**Is your feature request related to a problem? Please describe.**
Currently it's not obvious how the release process went

**Describe the solution you'd like**
It would be great to have Github Actions CI configured, that would run tests / and publish to NPM. The workflow YAML file would be a working example how to properly build the package + it is visible when the build fails.

**Comment by mindreframer** [comment]
Hey @oscarpas, I try to use your library and hit some obstacles. First of all: thanks for putting it out there, I think your approach to CSS-in-JS is really nice, especially the focus on type-safety. I hope my feedback reflects on the real user experience and it's not some obscure bug on my system. 

Here are the issues, I tried to provide enough info to be able to reproduce it  - https://github.com/oscarpas/panache/issues/15 and https://github.com/oscarpas/panache/issues/14

Thanks and all the best!

**Comment by oscarpas** [comment]
Hey @mindreframer, I'm glad you found the project interesting and that you took the time to provide some feedback, I appreciate it. Your other issues should be resolved, let me know if you run into any other problems!

Regarding the build and release process I'm currently handling that locally with Lerna. Since it's a monorepo each package can be released individually, not sure if that can be solved with GH actions. I agree that it could be more descriptive, it would be nice to get version, test coverage, size etc visualized with badges.

All the best!
